local L = LibStub("AceLocale-3.0"):NewLocale("RaidLeader", "enUS", true)

if L then
	-- button	
	L["RL_BUTTON_BLOODLUST"] = "Bloodlust"
	L["RL_BUTTON_COMBAT_RESS"] = "CR"
	L["RL_BUTTON_CURE_DISEASE"]  = "Disease"
	L["RL_BUTTON_CURE_POISON"]  = "Poison"
	L["RL_BUTTON_CURE_CURSE"]  = "Curse"
	L["RL_BUTTON_DISPELL"] = "Magic"
	L["RL_BUTTON_DPS_ADD"]  = "ADD"
	L["RL_BUTTON_MOVE_UR_ASS"] = "MOVE"
	L["RL_BUTTON_READYCHECK"] = "RC"
	L["RL_BUTTON_STOP_DPS"] = "NO DPS"
	L["RL_BUTTON_SUMMON"] = "SUMM"
	L["RL_BUTTON_BUFF"] = "Buff"
	L["RL_BUTTON_FOOD"] = "Food"
	L["RL_BUTTON_MS_CHANGE"] = "MS Change"
	L["RL_BUTTON_RAID_START"] = "Start"
	L["RL_BUTTON_ROLL_NOW"] = "Roll"
	L["RL_BUTTON_HERO_MODE"] = "HC"
	L["RL_BUTTON_SOULSTONE"] = "Stone"
	L["RL_BUTTON_PONY_OFF"] = "PonyOff"
	L["RL_BUTTON_WIPE"]  = "Wipe"
	L["RL_BUTTON_DISARM_TRAP"]  = "Disarm"
	L["RL_BUTTON_MD_TOT"]  = "MD/TOT"
	L["RL_BUTTON_CYCLONE"]  = "Cyclone"
	L["RL_BUTTON_TYPOON"]  = "Typoon"
	L["RL_BUTTON_DEVANDRA"]  = "Devandra"
	L["RL_BUTTON_SHACKLE"]  = "Shackle"
	L["RL_BUTTON_FROST_TRAP"]  = "FrostTrap"
	L["RL_BUTTON_TANK_AGGRO"]  = "Aggro"
	L["RL_BUTTON_HOP"]  = "HOP"
	L["RL_BUTTON_BOF"]  = "BOF"

	L["RL_BUTTON_CLEAR_ICONS"] = "Clear Marks"
	L["RL_BUTTON_CLOSE"]  = "Close"
	L["RL_BUTTON_FLOOD_OFF"] = "Stop Ad"
	L["RL_BUTTON_FLOOD_ON"] = "Ad Raider"
	L["RL_BUTTON_INVITE"] = ""
	L["RL_BUTTON_KICK"] = ""
	L["RL_BUTTON_LOOT_THRESHOLD2"] = ""
	L["RL_BUTTON_LOOT_THRESHOLD3"] = ""
	L["RL_BUTTON_LOOT_THRESHOLD4"] = ""
	L["RL_BUTTON_MASTER_LOOT"] = ""
	L["RL_BUTTON_SET_LEADER"] = ""
	L["RL_BUTTON_GROUP_LOOT"] = ""
	L["RL_BUTTON_FREEFORALL_LOOT"] = ""
	L["RL_BUTTON_TRANSPARENCY"] = "-"

	-- text
	L["RL_TEXT_RAID_WARNINGS"] = "Raid Warning"

	-- combat msg
	L["RL_BUTTON_BLOODLUST_MSG"] = "Use Bloodlust(Heroism) NOW. BL! BL!"
	L["RL_BUTTON_COMBAT_RESS_MSG"] = "Druid - Use Combat Ress in order"
	L["RL_BUTTON_CURE_DISEASE_MSG"]  = "Priest/Pally - Cure Disease"
	L["RL_BUTTON_CURE_POISON_MSG"]  = "Druid/Shammy/Pally - Cure Poison"
	L["RL_BUTTON_CURE_CURSE_MSG"]  = "Mage/Druid - Cure Curse"
	L["RL_BUTTON_DISPELL_MSG"] = "Priest - use Mass Dispell"
	L["RL_BUTTON_DPS_ADD_MSG"]  = "DPS ADD!!! ADD first!!! NO BOSS"
	L["RL_BUTTON_MOVE_UR_ASS_MSG"] = "Hurry up! Move your feet!!"
	L["RL_BUTTON_READYCHECK_MSG"] = "Ready Check!! AFK => KICK"
	L["RL_BUTTON_STOP_DPS_MSG"] = "STOP DPS!! STOP DPS!! STOP DPS!!"
	L["RL_BUTTON_SUMMON_MSG"] = "Lock, Please Summon Stone"
	L["RL_BUTTON_BUFF_MSG"] = ""
	L["RL_BUTTON_FOOD_MSG"] = "Mage - Drink, Lock - Candy, Anyone has a FISH!!"
	L["RL_BUTTON_MS_CHANGE_MSG"] = "Wisp MS Change if you want"
	L["RL_BUTTON_RAID_START_MSG"] = "Listen!! Roll items about 30 mins before expired or at RO. Respect the DBM timer. AFK lose item"
	L["RL_BUTTON_ROLL_NOW_MSG"] = "Roll item now."
	L["RL_BUTTON_HERO_MODE_MSG"] = "Can Anyone change it to HC?"
	L["RL_BUTTON_SOULSTONE_MSG"] = "Lock, please put soul stone on Tanker or Healer"
	L["RL_BUTTON_PONY_OFF_MSG"] = "Hunter/Pally turn off the PACK Aspect/PONY auroa"
	L["RL_BUTTON_WIPE_MSG"]  = "Quickly Wipe. Healers don't heal. Quickly move back. Pally use bubble if you can."
	L["RL_BUTTON_DISARM_TRAP_MSG"]  = "Rogue, Disarm any trap!!!"
	L["RL_BUTTON_MD_TOT_MSG"]  = "Hunter/Rogue, use MD/TOT on tanker"
	L["RL_BUTTON_CYCLONE_MSG"]  = "Druid, use Cyclone on mind controlled one."
	L["RL_BUTTON_TYPOON_MSG"]  = "Balance - use Typoon on ADD in front of you"
	L["RL_BUTTON_DEVANDRA_MSG"]  = "Priest or Mage -- take Devandra with sheep or MC"
	L["RL_BUTTON_SHACKLE_MSG"]  = "Priest/Pally use Shackle or Repentance"
	L["RL_BUTTON_FROST_TRAP_MSG"]  = "Hunter, put FrostTrap on the stair"
	L["RL_BUTTON_TANK_AGGRO_MSG"]  = "Tanker, get the Aggro!!! Come on..."
	L["RL_BUTTON_HOP_MSG"]  = "Pally, use Hands of Protection"
	L["RL_BUTTON_BOF_MSG"]  = "Pally, use Blessing of Freedom on TANK"
	L["RL_BUTTON_CLEAR_ICONS_MSG"] = ""
	L["RL_BUTTON_CLOSE_MSG"]  = ""
	L["RL_BUTTON_FLOOD_OFF_MSG"] = ""
	L["RL_BUTTON_FLOOD_ON_MSG"] = ""
	L["RL_BUTTON_INVITE_MSG"] = ""
	L["RL_BUTTON_KICK_MSG"] = ""
	L["RL_BUTTON_LOOT_THRESHOLD2_MSG"] = ""
	L["RL_BUTTON_LOOT_THRESHOLD3_MSG"] = ""
	L["RL_BUTTON_LOOT_THRESHOLD4_MSG"] = ""
	L["RL_BUTTON_MASTER_LOOT_MSG"] = ""
	L["RL_BUTTON_GROUP_LOOT_MSG"] = ""
	L["RL_BUTTON_FREEFORALL_LOOT_MSG"] = ""
	L["RL_BUTTON_SET_LEADER_MSG"] = ""
	L["RL_BUTTON_TRANSPARENCY_MSG"] = ""

	-- tooltip
	L["RL_BUTTON_BLOODLUST_TOOLTIP"] = "Raid warning - \'" .. L["RL_BUTTON_BLOODLUST_MSG"] .. "\'"
	L["RL_BUTTON_COMBAT_RESS_TOOLTIP"] = "Raid warning - \'" .. L["RL_BUTTON_COMBAT_RESS_MSG"] .. "\'"
	L["RL_BUTTON_CURE_DISEASE_TOOLTIP"]  = "Raid warning - \'" .. L["RL_BUTTON_CURE_DISEASE_MSG"] .. "\'"
	L["RL_BUTTON_CURE_POISON_TOOLTIP"]  = "Raid warning - \'" .. L["RL_BUTTON_CURE_POISON_MSG"] .. "\'"
	L["RL_BUTTON_CURE_CURSE_TOOLTIP"]  = "Raid warning - \'" .. L["RL_BUTTON_CURE_CURSE_MSG"] .. "\'"
	L["RL_BUTTON_DISPELL_TOOLTIP"] = "Raid warning - \'" .. L["RL_BUTTON_DISPELL_MSG"] .. "\'"
	L["RL_BUTTON_DPS_ADD_TOOLTIP"]  = "Raid warning - \'" .. L["RL_BUTTON_DPS_ADD_MSG"] .. "\'"
	L["RL_BUTTON_MOVE_UR_ASS_TOOLTIP"] = "Raid warning - \'" .. L["RL_BUTTON_MOVE_UR_ASS_MSG"] .. "\'"
	L["RL_BUTTON_READYCHECK_TOOLTIP"] = "Raid warning - \'" .. L["RL_BUTTON_READYCHECK_MSG"] .. "\'"
	L["RL_BUTTON_STOP_DPS_TOOLTIP"] = "Raid warning - \'" .. L["RL_BUTTON_STOP_DPS_MSG"] .. "\'"
	L["RL_BUTTON_SUMMON_TOOLTIP"] = "Raid warning - \'" .. L["RL_BUTTON_SUMMON_MSG"] .. "\'"
	L["RL_BUTTON_BUFF_TOOLTIP"] = "Raid warning - order buff msg"
	L["RL_BUTTON_FOOD_TOOLTIP"] = "Raid warning - \'" .. L["RL_BUTTON_FOOD_MSG"] .. "\'"
	L["RL_BUTTON_MS_CHANGE_TOOLTIP"] = "Raid warning - \'" .. L["RL_BUTTON_MS_CHANGE_MSG"] .. "\'"
	L["RL_BUTTON_RAID_START_TOOLTIP"] = "Raid warning - \'" .. L["RL_BUTTON_RAID_START_MSG"] .. "\'"
	L["RL_BUTTON_ROLL_NOW_TOOLTIP"] = "Raid warning - \'" .. L["RL_BUTTON_ROLL_NOW_MSG"] .. "\'"
	L["RL_BUTTON_HERO_MODE_TOOLTIP"] = "Raid warning - \'" .. L["RL_BUTTON_HERO_MODE_MSG"] .. "\'"
	L["RL_BUTTON_SOULSTONE_TOOLTIP"] = "Raid warning - \'" .. L["RL_BUTTON_SOULSTONE_MSG"] .. "\'"
	L["RL_BUTTON_PONY_OFF_TOOLTIP"] = "Raid warning - \'" .. L["RL_BUTTON_PONY_OFF_MSG"] .. "\'"
	L["RL_BUTTON_WIPE_TOOLTIP"] = "Raid warning - \'" .. L["RL_BUTTON_WIPE_MSG"] .. "\'"
	L["RL_BUTTON_DISARM_TRAP_TOOLTIP"] = "Raid warning - \'" .. L["RL_BUTTON_DISARM_TRAP_MSG"] .. "\'"
	L["RL_BUTTON_MD_TOT_TOOLTIP"]  = "Raid warning - \'" .. L["RL_BUTTON_MD_TOT_MSG"] .. "\'"
	L["RL_BUTTON_CYCLONE_TOOLTIP"] = "Raid warning - \'" .. L["RL_BUTTON_CYCLONE_MSG"] .. "\'"
	L["RL_BUTTON_TYPOON_TOOLTIP"]  = "Raid warning - \'" .. L["RL_BUTTON_TYPOON_MSG"] .. "\'"
	L["RL_BUTTON_DEVANDRA_TOOLTIP"] = "Raid warning - \'" .. L["RL_BUTTON_DEVANDRA_MSG"] .. "\'"
	L["RL_BUTTON_SHACKLE_TOOLTIP"]  = "Raid warning - \'" .. L["RL_BUTTON_SHACKLE_MSG"] .. "\'"
	L["RL_BUTTON_FROST_TRAP_TOOLTIP"]  = "Raid warning - \'" .. L["RL_BUTTON_FROST_TRAP_MSG"] .. "\'"
	L["RL_BUTTON_TANK_AGGRO_TOOLTIP"]  = "Raid warning - \'" .. L["RL_BUTTON_TANK_AGGRO_MSG"] .. "\'"
	L["RL_BUTTON_HOP_TOOLTIP"]  = "Raid warning - \'" .. L["RL_BUTTON_HOP_MSG"] .. "\'"
	L["RL_BUTTON_BOF_TOOLTIP"]  = "Raid warning - \'" .. L["RL_BUTTON_BOF_MSG"] .. "\'"
	
	L["RL_BUTTON_CLEAR_ICONS_TOOLTIP"] = "Clear Marks"
	L["RL_BUTTON_CLOSE_TOOLTIP"]  = "Close the Addon"
	L["RL_BUTTON_FLOOD_OFF_TOOLTIP"] = "turn off finding people"
	L["RL_BUTTON_FLOOD_ON_TOOLTIP"] = "find the raiders"
	L["RL_BUTTON_INVITE_TOOLTIP"] = "Invite target player"
	L["RL_BUTTON_KICK_TOOLTIP"] = "Kick target from raid or group"
	L["RL_BUTTON_LOOT_THRESHOLD2_TOOLTIP"] = "Set loot threshold to uncommon"
	L["RL_BUTTON_LOOT_THRESHOLD3_TOOLTIP"] = "Set loot threshold to rare"
	L["RL_BUTTON_LOOT_THRESHOLD4_TOOLTIP"] = "Set loot threshold to epic"
	L["RL_BUTTON_MASTER_LOOT_TOOLTIP"] = "Set to master loot"
	L["RL_BUTTON_GROUP_LOOT_TOOLTIP"] = "Set to group loot"
	L["RL_BUTTON_FREEFORALL_LOOT_TOOLTIP"] = "Set to free for all"
	L["RL_BUTTON_SET_LEADER_TOOLTIP"] = "Promote target to leader"
	L["RL_BUTTON_TRANSPARENCY_TOOLTIP"] = "Change Transperency - use left/right mouse click"

end
