local L = LibStub("AceLocale-3.0"):NewLocale("RaidLeader", "koKR", false)

if L then
	-- button	
	L["RL_BUTTON_BLOODLUST"] = "블러드"
	L["RL_BUTTON_COMBAT_RESS"] = "전부"
	L["RL_BUTTON_CURE_DISEASE"]  = "질병"
	L["RL_BUTTON_CURE_POISON"]  = "독"
	L["RL_BUTTON_CURE_CURSE"]  = "저주"
	L["RL_BUTTON_DISPELL"] = "마법"
	L["RL_BUTTON_DPS_ADD"]  = "공격애드"
	L["RL_BUTTON_SUMMON"] = "SUMM"
	L["RL_BUTTON_BUFF"] = "Buff"
	L["RL_BUTTON_FOOD"] = "Food"
	L["RL_BUTTON_MS_CHANGE"] = "MS Change"
	L["RL_BUTTON_RAID_START"] = "Start"
	L["RL_BUTTON_ROLL_NOW"] = "Roll"
	L["RL_BUTTON_HERO_MODE"] = "HC"
	L["RL_BUTTON_SOULSTONE"] = "Stone"
	L["RL_BUTTON_PONY_OFF"] = "PonyOff"
	L["RL_BUTTON_WIPE"]  = "Wipe"
	L["RL_BUTTON_DISARM_TRAP"]  = "Disarm"
	L["RL_BUTTON_MD_TOT"]  = "MD/TOT"
	L["RL_BUTTON_CYCLONE"]  = "Cyclone"
	L["RL_BUTTON_TYPOON"]  = "Typoon"
	L["RL_BUTTON_DEVANDRA"]  = "Devandra"
	L["RL_BUTTON_SHACKLE"]  = "Shackle"
	L["RL_BUTTON_FROST_TRAP"]  = "FrostTrap"
	L["RL_BUTTON_TANK_AGGRO"]  = "Aggro"
	L["RL_BUTTON_HOP"]  = "HOP"
	L["RL_BUTTON_HOF"]  = "HOF"

	L["RL_BUTTON_CLEAR_ICONS"] = "아이콘삭제"
	L["RL_BUTTON_CLOSE"]  = "닫기"
	L["RL_BUTTON_FLOOD_OFF"] = "광고취소"
	L["RL_BUTTON_FLOOD_ON"] = "공대모집"
	L["RL_BUTTON_GROUP_LOOT"] = "주사위"
	L["RL_BUTTON_FREEFORALL_LOOT"] = "자유획득"
	L["RL_BUTTON_LOOT_THRESHOLD2"] = "고급아이템"
	L["RL_BUTTON_LOOT_THRESHOLD3"] = "휘귀아이템"
	L["RL_BUTTON_LOOT_THRESHOLD4"] = "영웅아이템"
	L["RL_BUTTON_MASTER_LOOT"] = "담당자획득"
	L["RL_BUTTON_MOVE_UR_ASS"] = "이동"
	L["RL_BUTTON_READYCHECK"] = "전투준비"
	L["RL_BUTTON_SET_LEADER"] = "공장변경"
	L["RL_BUTTON_STOP_DPS"] = "딜금지"
	L["RL_BUTTON_TRANSPARENCY"] = "-"


	-- text
	L["RL_TEXT_RAID_WARNINGS"] = "공대 메세지"

	-- combat msg
	L["RL_BUTTON_BLOODLUST_MSG"] = "주술님 - 블러드!! 블러드!! 블러드!!"
	L["RL_BUTTON_COMBAT_RESS_MSG"] = "드루님 - 전투 부활해주세요. (탱/힐/딜 우선순위)"
	L["RL_BUTTON_CURE_DISEASE_MSG"]  = "사제님/기사님 - 질병해제 해주세요."
	L["RL_BUTTON_CURE_POISON_MSG"]  = "드루님/주술님/기사님 - 독해제 해주세요"
	L["RL_BUTTON_CURE_CURSE_MSG"]  = "법사님/드루님 - 저주해제 해주세요."
	L["RL_BUTTON_DISPELL_MSG"] = "사제님 - 대규모 무효화 해주세요."
	L["RL_BUTTON_DPS_ADD_MSG"]  = "애드(잡몹/ADD) 부터 공격!!! "
	L["RL_BUTTON_MOVE_UR_ASS_MSG"] = "빨리 움직여주세요."
	L["RL_BUTTON_READYCHECK_MSG"] = "전투준비 확인 후 시작합니다."
	L["RL_BUTTON_STOP_DPS_MSG"] = "딜 금지!!!! 공격 중지!!! - 힐님은 탱힐하세요."
	L["RL_BUTTON_SUMMON_MSG"] = "흑마님, 소환문 부탁합니다."
	L["RL_BUTTON_BUFF_MSG"] = ""
	L["RL_BUTTON_FOOD_MSG"] = "법사님 - 물빵, 흑마님 - 사탕, 생선통구이 부탁드립니다."
	L["RL_BUTTON_MS_CHANGE_MSG"] = "주특 변경하실 분 귓말 주세요."
	L["RL_BUTTON_RAID_START_MSG"] = "레이드 시작합니다. 다들 영약 및 버프 확인해주시고, dbm 타이머에 맞춰서 공격해주세요."
	L["RL_BUTTON_ROLL_NOW_MSG"] = "아이템 분배시작합니다."
	L["RL_BUTTON_HERO_MODE_MSG"] = "영웅모드로 변경가능하신 분??"
	L["RL_BUTTON_SOULSTONE_MSG"] = "흑마님, 영석을 탱/힐 중 한분에게 주세요."
	L["RL_BUTTON_PONY_OFF_MSG"] = "냥꾼님/기사님, 치무상/성전사 오라 제거해주세요."
	L["RL_BUTTON_WIPE_MSG"]  = "WIPE!!! 실패했습니다. 릴리즈하시고 빨리 입성해주세요."
	L["RL_BUTTON_DISARM_TRAP_MSG"]  = "도적님! 아시죠.. 트랩제거해주세요."
	L["RL_BUTTON_MD_TOT_MSG"]  = "낭꾼님/도적님, 눈속/속거 보스탱에게 주세요."
	L["RL_BUTTON_CYCLONE_MSG"]  = "드루님, 정배 대상자에게 사이클론!!!"
	L["RL_BUTTON_TYPOON_MSG"]  = "조드님, 애드에게 태풍!! 태풍!!"
	L["RL_BUTTON_DEVANDRA_MSG"]  = "지정된 암사님/법사님, 왼쪽에 나오는 데반드라 정배 또는 양변해주세요."
	L["RL_BUTTON_SHACKLE_MSG"]  = "사제님/기사님 중 한 분 해골 마크에게 속박/참회 해주세요."
	L["RL_BUTTON_FROST_TRAP_MSG"]  = "냥꾼님, 애드 나오기 5초전에 얼덫을 계단에 설치해주세요."
	L["RL_BUTTON_TANK_AGGRO_MSG"]  = "탱커님, 어글 잡아주세요. 어글 빨리.... 낭꾼/도적님 눈속/속거 도움주세요."
	L["RL_BUTTON_HOP_MSG"]  = "기사님, 보손!!! 보손!!!"
	L["RL_BUTTON_HOF_MSG"]  = "기사님, 탱커에게 자손!!! 자손!!!"

	L["RL_BUTTON_CLEAR_ICONS_MSG"] = ""
	L["RL_BUTTON_CLOSE_MSG"]  = ""
	L["RL_BUTTON_FLOOD_OFF_MSG"] = ""
	L["RL_BUTTON_FLOOD_ON_MSG"] = ""
	L["RL_BUTTON_LOOT_THRESHOLD2_MSG"] = ""
	L["RL_BUTTON_LOOT_THRESHOLD3_MSG"] = ""
	L["RL_BUTTON_LOOT_THRESHOLD4_MSG"] = ""
	L["RL_BUTTON_MASTER_LOOT_MSG"] = "님이 전리품 담당자로 지정되었습니다."
	L["RL_BUTTON_GROUP_LOOT_MSG"] = ""
	L["RL_BUTTON_FREEFORALL_LOOT_MSG"] = ""
	L["RL_BUTTON_SET_LEADER_MSG"] = "레이드에 있는 타겟을 지정하고 설정해주세요."
	L["RL_BUTTON_TRANSPARENCY_MSG"] = ""
end

local TL = LibStub("AceLocale-3.0"):NewLocale("RaidLeaderToolTip", "koKR", false)
      L  = LibStub("AceLocale-3.0"):GetLocale("RaidLeader", true)

if TL and L then
	-- tooltip
	TL["RL_BUTTON_BLOODLUST_TOOLTIP"] = "\'" .. L["RL_BUTTON_BLOODLUST_MSG"] .. "\' 를 공격대 경보한다."
	TL["RL_BUTTON_COMBAT_RESS_TOOLTIP"] = "\'" .. L["RL_BUTTON_COMBAT_RESS_MSG"] .. "\' 를 공격대 경보한다." 
	TL["RL_BUTTON_CURE_DISEASE_TOOLTIP"] = "\'" .. L["RL_BUTTON_CURE_DISEASE_MSG"] .. "\' 를 공격대 경보한다."
	TL["RL_BUTTON_CURE_POISON_TOOLTIP"] = "\'" .. L["RL_BUTTON_CURE_POISON_MSG"] .. "\' 를 공격대 경보한다."
	TL["RL_BUTTON_CURE_CURSE_TOOLTIP"] = "\'" .. L["RL_BUTTON_CURE_CURSE_MSG"] .. "\' 를 공격대 경보한다."
	TL["RL_BUTTON_DISPELL_TOOLTIP"] = "\'" .. L["RL_BUTTON_DISPELL_MSG"] .. "\' 를 공격대 경보한다."
	TL["RL_BUTTON_DPS_ADD_TOOLTIP"] = "\'" .. L["RL_BUTTON_DPS_ADD_MSG"] .. "\' 를 공격대 경보한다."
	TL["RL_BUTTON_MOVE_UR_ASS_TOOLTIP"] = "\'" .. L["RL_BUTTON_MOVE_UR_ASS_MSG"] .. "\' 를 공격대 경보한다."
	TL["RL_BUTTON_READYCHECK_TOOLTIP"] = "\'" .. L["RL_BUTTON_READYCHECK_MSG"] .. "\' 를 공격대 경보한다."
	TL["RL_BUTTON_STOP_DPS_TOOLTIP"] = "\'" .. L["RL_BUTTON_STOP_DPS_MSG"] .. "\' 를 공격대 경보한다."
	TL["RL_BUTTON_SUMMON_TOOLTIP"] = "\'" .. L["RL_BUTTON_SUMMON_MSG"] .. "\' 를 공격대 경보한다."
	TL["RL_BUTTON_BUFF_TOOLTIP"] = "버프할 것에 대해서 공격대 경보한다."
	TL["RL_BUTTON_FOOD_TOOLTIP"] = "\'" .. L["RL_BUTTON_FOOD_MSG"] .. "\' 를 공격대 경보한다."
	TL["RL_BUTTON_MS_CHANGE_TOOLTIP"] = "\'" .. L["RL_BUTTON_MS_CHANGE_MSG"] .. "\' 를 공격대 경보한다."
	TL["RL_BUTTON_RAID_START_TOOLTIP"] = "\'" .. L["RL_BUTTON_RAID_START_MSG"] .. "\' 를 공격대 경보한다."
	TL["RL_BUTTON_ROLL_NOW_TOOLTIP"] = "\'" .. L["RL_BUTTON_ROLL_NOW_MSG"] .. "\' 를 공격대 경보한다."
	TL["RL_BUTTON_HERO_MODE_TOOLTIP"] = "\'" .. L["RL_BUTTON_HERO_MODE_MSG"] .. "\' 를 공격대 경보한다."
	TL["RL_BUTTON_SOULSTONE_TOOLTIP"] = "\'" .. L["RL_BUTTON_SOULSTONE_MSG"] .. "\' 를 공격대 경보한다."
	TL["RL_BUTTON_PONY_OFF_TOOLTIP"] = "\'" .. L["RL_BUTTON_PONY_OFF_MSG"] .. "\' 를 공격대 경보한다."
	TL["RL_BUTTON_WIPE_TOOLTIP"] = "\'" .. L["RL_BUTTON_WIPE_MSG"] .. "\' 를 공격대 경보한다."
	TL["RL_BUTTON_DISARM_TRAP_TOOLTIP"] = "\'" .. L["RL_BUTTON_DISARM_TRAP_MSG"] .. "\' 를 공격대 경보한다."
	TL["RL_BUTTON_MD_TOT_TOOLTIP"]  = "\'" .. L["RL_BUTTON_MD_TOT_MSG"] .. "\' 를 공격대 경보한다."
	TL["RL_BUTTON_CYCLONE_TOOLTIP"] = "\'" .. L["RL_BUTTON_CYCLONE_MSG"] .. "\' 를 공격대 경보한다."
	TL["RL_BUTTON_TYPOON_TOOLTIP"]  = "\'" .. L["RL_BUTTON_TYPOON_MSG"] .. "\' 를 공격대 경보한다."
	TL["RL_BUTTON_DEVANDRA_TOOLTIP"] = "\'" .. L["RL_BUTTON_DEVANDRA_MSG"] .. "\' 를 공격대 경보한다."
	TL["RL_BUTTON_SHACKLE_TOOLTIP"]  = "\'" .. L["RL_BUTTON_SHACKLE_MSG"] .. "\' 를 공격대 경보한다."
	TL["RL_BUTTON_FROST_TRAP_TOOLTIP"]  = "\'" .. L["RL_BUTTON_FROST_TRAP_MSG"] .. "\' 를 공격대 경보한다."
	TL["RL_BUTTON_TANK_AGGRO_TOOLTIP"]  = "\'" .. L["RL_BUTTON_TANK_AGGRO_MSG"] .. "\' 를 공격대 경보한다."
	TL["RL_BUTTON_HOP_TOOLTIP"]  = "\'" .. L["RL_BUTTON_HOP_MSG"] .. "\' 를 공격대 경보한다."
	TL["RL_BUTTON_HOF_TOOLTIP"]  = "\'" .. L["RL_BUTTON_HOF_MSG"] .. "\' 를 공격대 경보한다."

	TL["RL_BUTTON_CLEAR_ICONS_TOOLTIP"] = "전투 마크를 없앤다."
	TL["RL_BUTTON_CLOSE_TOOLTIP"]  = "해당 애드온을 닫는다."
	TL["RL_BUTTON_FLOOD_OFF_TOOLTIP"] = "공격대 광고를 중단한다."
	TL["RL_BUTTON_FLOOD_ON_TOOLTIP"] = "공격대 광고를 한다. (autoflood 이용)"
	TL["RL_BUTTON_LOOT_THRESHOLD2_TOOLTIP"] = "아이템 획득 조건을 고급아이템이상을 설정한다."
	TL["RL_BUTTON_LOOT_THRESHOLD3_TOOLTIP"] = "아이템 획득 조건을 휘귀아이템이상을 설정한다."
	TL["RL_BUTTON_LOOT_THRESHOLD4_TOOLTIP"] = "아이템 획득 조건을 영웅아이템이상을 설정한다."
	TL["RL_BUTTON_MASTER_LOOT_TOOLTIP"] = "해당 목표를 전리품 담당자로 지정한다."
	TL["RL_BUTTON_GROUP_LOOT_TOOLTIP"] = "주사위 획득으로 변경"
	TL["RL_BUTTON_FREEFORALL_LOOT_TOOLTIP"] = "자유 획득으로 변경"
	TL["RL_BUTTON_SET_LEADER_TOOLTIP"] = "해당 목표를 공장으로 지정합니다."
	TL["RL_BUTTON_TRANSPARENCY_TOOLTIP"] = "애드온창을 투명하게 합니다. (왼/오른 마우스 클릭)"
end

