local L = LibStub("AceLocale-3.0"):NewLocale("RaidLeader", "enUS", true)

if L then
	-- during raid - common
	L["RL_BUTTON_BLOODLUST"] = "Bloodlust"
	L["RL_BUTTON_COMBAT_RESS"] = "CR"
	L["RL_BUTTON_CURE_DISEASE"]  = "Disease"
	L["RL_BUTTON_CURE_POISON"]  = "Poison"
	L["RL_BUTTON_CURE_CURSE"]  = "Curse"
	L["RL_BUTTON_DISPELL"] = "Magic"
	L["RL_BUTTON_DPS_ADD"]  = "dps ADD"
	L["RL_BUTTON_MOVE_UR_ASS"] = "MOVE"
	L["RL_BUTTON_STOP_DPS"] = "NO DPS"
	L["RL_BUTTON_WIPE"]  = "Wipe"
	L["RL_BUTTON_MD_TOT"]  = "MD/TOT"
	L["RL_BUTTON_TANK_AGGRO"]  = "Aggro"
	L["RL_BUTTON_DPS_BOSS"] = "dps Boss"
	L["RL_BUTTON_RAID_OVER"] = "RO"

	-- boss
	L["RL_BUTTON_HOP"]  = "HOP"
	L["RL_BUTTON_HOF"]  = "HOF"
	L["RL_BUTTON_FROST_TRAP"]  = "FrostTrap"
	L["RL_BUTTON_CYCLONE"]  = "Cyclone"
	L["RL_BUTTON_TYPOON"]  = "Typoon"
	L["RL_BUTTON_DARNAVAN"]  = "DARNAVAN"
	L["RL_BUTTON_SHACKLE"]  = "Shackle"

	-- before raid
	L["RL_BUTTON_READYCHECK"] = "RC"
	L["RL_BUTTON_PONY_OFF"] = "PonyOff"
	L["RL_BUTTON_DISARM_TRAP"]  = "Disarm"
	L["RL_BUTTON_SUMMON"] = "SUMM"
	L["RL_BUTTON_PALADIN_BUFF"] = "P.Buff"
	L["RL_BUTTON_ETC_BUFF"] = "R.Buff"
	L["RL_BUTTON_FOOD"] = "Food"
	L["RL_BUTTON_MS_CHANGE"] = "Chg MS"
	L["RL_BUTTON_RAID_START"] = "Start"
	L["RL_BUTTON_ROLL_NOW"] = "Roll"
	L["RL_BUTTON_HERO_MODE"] = "HC"
	L["RL_BUTTON_SOULSTONE"] = "Stone"
	L["RL_BUTTON_PORTAL"] = "Portal"
	L["RL_BUTTON_SHARE_QUEST"] = "Quest"
	L["RL_BUTTON_DBM_PULL"] = "DBM Pull"
	L["RL_BUTTON_MS_CHANGE_NOTIFY"] = "Tell MS"

    -- marks
	L["RL_BUTTON_CLEAR_ICONS"] = "Clr Mark"


	-- general
	L["RL_BUTTON_FLOOD_OFF"] = "Stop Ad"
	L["RL_BUTTON_FLOOD_ON"] = "Ad Raider"
	L["RL_BUTTON_MASTER_LOOT"] = ""
	L["RL_BUTTON_SET_LEADER"] = ""
	L["RL_BUTTON_GROUP_LOOT"] = ""
	L["RL_BUTTON_FREEFORALL_LOOT"] = ""
	L["RL_BUTTON_SET_MT"] = "MT"
	L["RL_BUTTON_SET_OT"] = "OT"
	L["RL_BUTTON_NOTIFY_MT_OT"] = "MT/OT"

	L["RL_BUTTON_TRANSPARENCY"] = "-"
	L["RL_BUTTON_CLOSE"]  = "Close"
	L["RL_BUTTON_SET_HC_NM"] = "HC/NM"
	L["RL_CHECKBUTTON_NEED_HEALER"] = "Healer"
	L["RL_CHECKBUTTON_NEED_TANKER"] = "Tanker"
	L["RL_BUTTON_CALL_BOSS_FRAME"] = "BOSS"

	-- zone name
	L["EE10"] = "The Eye of Eternity - 10"
	L["UL10"] = "Ulduar - 10"
	L["OS10"] = "The Obsidian Sanctum - 10"
	L["VOA10"] = "Vault of Archavo - 10"
	L["NAXX10"] = "Naxxramas - 10"
	L["TOC10"] = "Trial of the Crusader - 10"
	L["ICC10"] = "Icecrown Citadel - 10"
	L["RS10"] = "The Ruby Sanctum - 10"
	L["EE25"] = "The Eye of Eternity - 25"
	L["UL25"] = "Ulduar - 25"
	L["OS25"] = "The Obsidian Sanctum - 25"
	L["VOA25"] = "Vault of Archavon - 25"
	L["NAXX25"] = "Naxxramas - 25"
	L["TOC25"] = "Trial of the Crusader - 25"
	L["ICC25"] = "Icecrown Citadel - 25"
	L["RS25"] = "The Ruby Sanctum - 25"

	-- print
	L["Choose instance first"] = "Choose instance first"
	L["Not In Instance, so just toggle"] = "Not In Instance, so just toggle"
	L["No Pally here"] = "No Pally here"
	L["Please join global channel and then try again"] = "Please join global channel and then try again"
	L["Please choose the raid instance"] = "Please choose the raid instance"
	L["Please type /mt to assign MT"] = "Please type /mt to assign MT (/clearmt for clear)"
	L["Please type /ma to assign OT"] = "Please type /ma to assign OT (/clearma for clear)"
	L["Click to toggle RaidLeader"] = "Click to toggle RaidLeader"
	L["Error failed to load LibGroupTalents"] = "failed to load LibGroupTalents from libs folder."
	L["Please choose the target"] = "Please choose the target"
	L["Reset MS Change Informations"] = "Reset MS Change Informations"
	L["Expire MS Change Time"] = "Expire MS Change Time(1min)"
	L["Error! Unknown # of beacon: "] = "Error! Unknown # of beacon: "

	L["Type your MS Change if you want"] = "Type your MS Change if you want"
	L["My MS Change"] = "My MS Change"
	L["Change Flood Msg"] = "Change Flood Msg"
	L["Type your flood msg if you want"] = "Type your flood msg if you want to change"
	L["Fatal - Failed to load roster info"] = "Fatal - Failed to load roster info"
	L["Please assign tanker with /mt /ma"] = "Please assign tanker with /mt for MT /ma for OT (/clearmt, /clearma for clear)"
	L["WOW Error! Need to relog!"] = "WOW Error! Need to relog!"
	L["ERROR - Failed to create button with "] = "ERROR - Failed to create button with "
	L["Drums of the Wild"] = "Use Drums"
	L["Use Korean"] = "Use Korean"
	L["Use SDBM"] = "Use Simple DBM"
	L["Update Raid Roaster Info"] = "Update Raid Roaster Info"

	-- boss
	L["Marrowgar"] = "Marrowgar"
	L["Lady"] = "Lady"
	L["GunShip"] = "GunShip"
	L["DeathBringer"] = "DeathBringer"
	L["Festergut"] = "Festergut"
	L["Rotface"] = "Rotface" 
	L["Professor"] = "Professor"
	L["Council"] = "Council"
	L["BloodQueen"] = "BloodQueen" 
	L["Dreamwalker"] = "Dreamwalker"
	L["Sindragosa"] = "Sindragosa"
	L["Lich King"] = "Lich King"

	L["ALL"] = "All"
	L["BOSS"] = "Boss"

	-- Naxxramas
	L["Anub\'Rekhan"] = "Anub\'Rekhan"
	L["Grand Widow Faerlina"] = "Faerlina"
	L["Maexxna"] = "Maexxna"
	L["Noth the Plaguebringer"] = "Noth"
	L["Heigan the Unclean"] = "Heigan"
	L["Loatheb"] = "Loatheb"
	L["Instructor Razuvious"] = "Instructor Razuvious"
	L["Gothik the Harvester"] = "Gothik the Harvester"
	L["The Four Horsemen"] = "The Four Horsemen"
	L["Patchwerk"] = "Patchwerk"
	L["Grobbulus"] = "Grobbulus"
	L["Gluth"] = "Gluth"
	L["Thaddius"] = "Thaddius"
	L["Sapphiron"] = "Sapphiron"
	L["Kel\'Thuzad"] = "Kel\'Thuzad"

	-- VOA
	L["Ice Watcher"] = "Toravon, Ice"
	L["Flame Watcher"] = "Koralon, Fire"
	L["Storm Watcher"] = "Emalon, Storm"
	L["Stone Watcher"] = "Archavon, Stone"

	-- Ulduar
	L["Flame Leviathan"] = "Flame Leviathan"
	L["Ignis the Furnace Master"] = "Ignis"
	L["Razorscale"] = "Razorscale"
	L["XT-002 Deconstructor"] = "XT-002"
	L["Assembly of Iron"] = "Assembly of Iron"
	L["Kologarn"] = "Kologarn"
	L["Auriaya"] = "Auriaya"
	L["Freya"] = "Freya"
	L["Hodir"] = "Hodir"
	L["Mimiron"] = "Mimiron"
	L["Thorim"] = "Thorim"
	L["General Vezax"] = "General Vezax"
	L["Yogg-Saron"] = "Yogg-Saron"
	L["Algalon the Observer"] = "Algalon"

	-- RS
	L["General Zarithrian"] = "Zarithrian"
	L["Baltharus the Warborn"] = "Baltharus"
	L["Saviana Ragefire"] = "Saviana Ragefire"
	L["Halion"] = "Halion"

	-- TOC
	L["Northrend Beasts"] = "Northrend Beasts"
	L["Lord Jaraxxus"] = "Lord Jaraxxus"
	L["Champions"] = "Champions"
	L["Twin Val\'kyr"] = "Twin Val\'kyr"
	L["Anub\'arak"] = "Anub\'arak"
end

